### ISSUE TITLE
Issue with output of SAVer

### ISSUE THREAD

**Issue by harshithnarra** [svm-abstract-verifier/saver#5]
When I run SAVer the label column is blank in the output and the correct cases is shown as zero. When I run the same model with the test set it gives accuracy of 70 percent.
I tried and checked both the data and the model files to check if there is any issue there but couldn't find any issue.
Could you please help me figure out what the issue could be.

**Comment by harshithnarra** [comment]
The following link has screenshot of the output, data and model file for reference:
https://drive.google.com/drive/folders/1h97-iYLF7eGfvPREtmz4U38h1vfJ4Q9l

**Comment by marco-zanella** [comment]
Thank you for you report, I tried downloading the sample material you provided, and noticed that the SAVer_data1.csv file starts with
`# 19 7,,,,,,,`
rather than
`# 19 7`
I tried changing the heading to the latter, which seems to produce the correct result with 100% accuracy. Could you confirm this is the issue?

**Comment by harshithnarra** [comment]
Thanks, that worked.
But also my SVM model has other hyperparameters like C and weights of the classes, how can I set these hyperparameters.
Is there a way?
